export const GET_TEACHER_CLASSROOM = 'GET_TEACHER_CLASSROOM'
export const REMOVE_TEACHER_CLASSROOM = 'REMOVE_TEACHER_CLASSROOM'
export const GET_ALL_EXAMS = 'GET_ALL_EXAMS'
export const REMOVE_EXAM = 'REMOVE_EXAM'